export const StudendSampleData =
[
    {
       "FirstName":"Ram",
       "LastName":"",
       "Department":"IT",
       "Year":"2022",
       "StudnetRollNo":"std000100"
    },
    {
       "FirstName":"Anu",
       "LastName":"",
       "Department":"IT",
       "Year":"2022",
       "StudnetRollNo":"std000101"
    },
    {
       "FirstName":"Abu",
       "LastName":"",
       "Department":"IT",
       "Year":"2022",
       "StudnetRollNo":"std000102"
    },
    {
       "FirstName":"Binu",
       "LastName":"",
       "Department":"IT",
       "Year":"2022",
       "StudnetRollNo":"std000103"
    },
    {
       "FirstName":"Mathew",
       "LastName":"",
       "Department":"CSE",
       "Year":"2022",
       "StudnetRollNo":"std000104"
    },
    {
       "FirstName":"Nazir",
       "LastName":"",
       "Department":"CSE",
       "Year":"2022",
       "StudnetRollNo":"std000105"
    },
    {
       "FirstName":"Suresh",
       "LastName":"",
       "Department":"CSE",
       "Year":"2022",
       "StudnetRollNo":"std000106"
    },
    {
       "FirstName":"Pravin",
       "LastName":"",
       "Department":"CSE",
       "Year":"2022",
       "StudnetRollNo":"std000107"
    },
    {
       "FirstName":"Harish",
       "LastName":"",
       "Department":"BCA",
       "Year":"2022",
       "StudnetRollNo":"std000108"
    },
    {
       "FirstName":"Vijay",
       "LastName":"",
       "Department":"BCA",
       "Year":"2022",
       "StudnetRollNo":"std000109"
    },
    {
       "FirstName":"Hari",
       "LastName":"",
       "Department":"BCA",
       "Year":"2022",
       "StudnetRollNo":"std000110"
    },
    {
       "FirstName":"Daniel",
       "LastName":"",
       "Department":"BCA",
       "Year":"2022",
       "StudnetRollNo":"std000111"
    }
 ]
 